---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/tulioad6/public_html/
    - export REPOPATH=/home2/tulioad6/repositories/tulioadv
    - cd $REPOPATH
    - /usr/bin/rsync -av --delete \
      --exclude='scss/' \
      --exclude='node_modules/' \
      --exclude='package.json' \
      --exclude='package-lock.json' \
      --exclude='.git/' \
      --exclude='.gitignore' \
      --exclude='.cpanel.yml' \
      --exclude='README.md' \
      --exclude='.DS_Store' \
      * $DEPLOYPATH
